server:
  port: 8000
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://localhost:3306/theaterdb?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: theaterdb 
    password: theaterdb
  
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      
  security:
    user:
      name: test
      password: 1234
file:
  path: C:/springTool/springWork/movie/src/main/webapp/WEB-INF/views